---
- hosts: localhost 
  gather_facts: false
  connection: local
  become: yes
  tasks:
    - name: Install Our Packages
      apt:
        name: ['apache2', 'mysql-server', 'mysql-common', 'mysql-client']
        state: present
        update_cache: true

    - name: Confirm services are running
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - apache2
        - mysql
        


